"use client";

import React, { createContext, useContext, useEffect, useState, ReactNode } from "react";

export type Language = "uz" | "ru" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
  isUZ: boolean;
  isRU: boolean;
  isEN: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  uz: {
    // Navigation
    "nav.home": "Bosh sahifa",
    "nav.lessons": "Darslar",
    "nav.quizzes": "Testlar",
    "nav.analytics": "Tahlillar",
    "nav.settings": "Sozlamalar",
    "nav.profile": "Profil",
    "nav.logout": "Chiqish",
    
    // Auth
    "auth.login": "Kirish",
    "auth.register": "Ro'yxatdan o'tish",
    "auth.email": "Email",
    "auth.password": "Parol",
    "auth.forgot_password": "Parolni unutdingizmi?",
    "auth.no_account": "Akkauntingiz yo'qmi?",
    "auth.has_account": "Akkauntingiz bormi?",
    "auth.name": "Ism",
    "auth.role": "Rol",
    "auth.student": "Talaba",
    "auth.professor": "Professor",
    
    // Lessons
    "lesson.create": "Dars yaratish",
    "lesson.join": "Darsga qo'shilish",
    "lesson.code": "Dars kodi",
    "lesson.active": "Faol darslar",
    "lesson.completed": "Tugallangan darslar",
    "lesson.start": "Boshlash",
    "lesson.pause": "Pauza",
    "lesson.resume": "Davom etish",
    "lesson.end": "Yakunlash",
    "lesson.title": "Dars nomi",
    "lesson.description": "Tavsif",
    "lesson.subject": "Fan",
    "lesson.students_count": "Talabalar soni",
    
    // Professor Lessons Page
    "lessons.title": "Mening darslarim",
    "lessons.subtitle": "Barcha darslaringizni boshqaring",
    "lessons.search": "Darslarni qidirish...",
    "lessons.filter_all": "Barchasi",
    "lessons.filter_active": "Faol",
    "lessons.filter_preparing": "Tayyorlanmoqda",
    "lessons.filter_completed": "Tugatilgan",
    "lessons.status_active": "Faol",
    "lessons.status_preparing": "Tayyorlanmoqda",
    "lessons.status_completed": "Tugatilgan",
    "lessons.students": "talaba",
    "lessons.minutes": "daqiqa",
    "lessons.progress": "Progress",
    "lessons.manage": "Boshqarish",
    "lessons.manage_panel": "Dars boshqaruv paneli tez orada ishga tushadi.",
    "lessons.not_found_title": "Darslar topilmadi",
    "lessons.not_found_search": "\"{query}\" bo'yicha natijalar yo'q",
    "lessons.not_found_empty": "Hali darslar yaratilmagan",
    
    // Mock Lessons Data
    "mock.lesson1.title": "Ma'lumotlar bazasi asoslari",
    "mock.lesson1.topic": "SQL va relational ma'lumotlar bazalari",
    "mock.lesson1.time": "Ertaga 14:00",
    "mock.lesson2.title": "Dasturiy ta'minot muhandisligi",
    "mock.lesson2.topic": "Agile metodologiyalar va SCRUM",
    "mock.lesson2.time": "Juma 10:00",
    "mock.lesson3.title": "Web dasturlash",
    "mock.lesson3.topic": "React va Next.js asoslari",
    "mock.lesson4.title": "Algoritm va ma'lumotlar tuzilmasi",
    "mock.lesson4.topic": "Sort, search va graph algoritmlar",
    "mock.lesson4.time": "Dushanba 09:00",
    
    // Live Session Page
    "live.title": "Jonli Dars",
    "live.status_live": "JONLI",
    "live.ended_title": "Dars yakunlandi",
    "live.ended_desc": "Analitika va natijalar tayyorlanmoqda...",
    "live.lesson_title": "Dars: Algoritmlar va Ma'lumotlar Tuzilmasi",
    "live.presentation_placeholder": "Prezentatsiya shu yerda ko'rsatiladi",
    "live.presentation_sub": "SlideViewer komponenti bilan ishlaydi",
    "live.room_info": "Xona ma'lumotlari",
    "live.room_id": "Xona ID",
    "live.students": "Talabalar",
    "live.students_connected": "ta ulangan",
    "live.time": "Vaqt",
    "live.quick_actions": "Tezkor harakatlar",
    "live.send_quiz": "Test savoli berish",
    "live.end_lesson": "Darsni tugatish",
    "live.quiz_sent_title": "Quiz savoli",
    "live.quiz_sent_desc": "Barcha talabalar ekraniga savol yuborildi!",
    
    // Components (Gauge, Poll)
    "gauge.polling": "So'rovnoma o'tkazing!",
    "gauge.wow_fact": "WOW fakt ko'rsating!",
    "gauge.interaction": "Talabalardan so'rang!",
    "gauge.title": "Diqqat Darajasi",
    "gauge.students": "talaba",
    "gauge.confusion": "Chalkashlik",
    "gauge.boredom": "Zerikish",
    "gauge.good": "Yaxshi holat",
    "poll.new": "Yangi So'rovnoma",
    "poll.placeholder": "Savol yozing...",
    "poll.option": "variant",
    "poll.start": "So'rovnomani Boshlash",
    "poll.live": "JONLI",
    "poll.votes": "ovoz",
    "poll.total": "Jami:",
    "poll.students": "talaba",
    "poll.end": "Yakunlash",
    "poll.wait": "So'rovnoma boshlanishini kuting...",
    "poll.voted": "✓ Ovozingiz qabul qilindi!",
    
    // Analytics Page
    "analytics.title": "Analitika",
    "analytics.this_week": "Ushbu Hafta",
    "analytics.filters": "Filtrlar",
    "analytics.download_pdf": "PDF Yuklash",
    "analytics.total_lessons": "Jami darslar",
    "analytics.avg_attention": "O'rtacha diqqat",
    "analytics.avg_quiz_score": "Test o'rtacha bali",
    "analytics.active_students": "Aktiv talabalar",
    "analytics.timeline_title": "Dars davomidagi o'rtacha diqqat (Timeline)",
    "analytics.critical_limit": "Kritik chegara (70%)",
    "analytics.heatmap_title": "Mavzular bo'yicha o'zlashtirish xaritasi",
    "analytics.student": "Talaba",
    "analytics.difficulty_title": "Savollar qiyinlik tahlili",
    "analytics.ai_recommendation": "AI Tavsiyasi",
    "analytics.ai_recommendation_desc": "Bu 2 ta savol (Q-12, Q-08) juda qiyin keldi. 'Kvant Entropiya' va 'Zichlik formulasi'ni qayta tushuntirishingiz tavsiya etiladi.",
    "analytics.activity_map_title": "Hafta kunlari va soatlar kesimida faollik xaritasi",
    "analytics.activity_map_insight": "💡 Sizning guruhingiz Chorshanba 10:00-12:00 oralig'ida eng yuqori diqqatni namoyon etadi.",
    "analytics.student_profile": "Talaba Profili",
    "analytics.active_student": "Faol talaba • 15 kunlik Streak 🔥",
    "analytics.personal_recommendation": "Shaxsiy tavsiya",
    "analytics.personal_recommendation_desc": "{name} 'Entropiya' mavzusida biroz qiynalmoqda (40%). Qo'shimcha materiallar yuborish tavsiya etiladi.",
    "analytics.telegram_msg": "Telegram orqali xabar yozish",
    "analytics.mastery_details": "O'zlashtirish tafsiloti",
    "analytics.mock.event_start": "Dars boshlandi",
    "analytics.mock.event_drop": "Diqqat pasaydi",
    "analytics.mock.event_quiz": "Jonli Quiz (Polling)",
    "analytics.mock.event_fatigue": "Charchoq",
    "analytics.mock.event_wow": "WOW Fakt ko'rsatildi",
    "analytics.mock.q1": "Q-12: Kvant Entropiya",
    "analytics.mock.q2": "Q-08: Zichlik formulasi",
    "analytics.mock.q3": "Q-03: Kinetik energiya",
    "analytics.mock.q4": "Q-01: Asosiy tushunchalar",
    "analytics.mock.topic1": "Termodinamika 1",
    "analytics.mock.topic2": "Termodinamika 2",
    "analytics.mock.topic3": "Entropiya",
    "analytics.mock.topic4": "Kinetika",
    
    // Students Page
    "students.title": "Talabalar",
    "students.subtitle": "Barcha talabalarning faoliyatini kuzating",
    "students.add_btn": "Talaba qo'shish",
    "students.error": "Xato",
    "students.name_email_required": "Ism va email majburiy",
    "students.added_title": "Talaba qo'shildi!",
    "students.added_desc": "{name} muvaffaqiyatli qo'shildi",
    "students.modal_title": "Yangi talaba qo'shish",
    "students.name_label": "Ism va familiya",
    "students.name_placeholder": "Ali Karimov",
    "students.email_label": "Email",
    "students.email_placeholder": "ali@univer.uz",
    "students.cancel": "Bekor qilish",
    "students.add": "Qo'shish",
    "students.profile_title": "Talaba profili",
    "students.streak_days": "kunlik seriya",
    "students.progress": "Progress",
    "students.courses": "Kurslar",
    "students.last_active": "So'nggi faollik:",
    "students.msg_sent_title": "Xabar yuborildi",
    "students.msg_sent_desc": "{name}ga email yuborildi",
    "students.send_msg": "Xabar yuborish",
    "students.report": "Hisobot",
    "students.report_desc": "Talaba hisoboti tayyor bo'lganda bildirishma keladi",
    "students.stat_total": "Jami talabalar",
    "students.stat_active": "Faol talabalar",
    "students.stat_progress": "O'rtacha progress",
    "students.stat_streak": "O'rtacha seriya",
    "students.search_placeholder": "Talabalarni qidirish...",
    "students.filter_all": "Barchasi",
    "students.filter_active": "Faol",
    "students.filter_inactive": "Nofaol",
    "students.col_student": "Talaba",
    "students.col_progress": "Progress",
    "students.col_streak": "Seriya",
    "students.col_courses": "Kurslar",
    "students.col_status": "Status",
    "students.col_perf": "Natija",
    "students.col_actions": "Amallar",
    "students.days": "kun",
    "students.perf_excellent": "A'lo",
    "students.perf_good": "Yaxshi",
    "students.perf_average": "O'rtacha",
    "students.perf_unknown": "Noma'lum",
    "students.btn_details": "Batafsil",
    "students.btn_msg": "Xabar",
    "students.not_found": "Talabalar topilmadi",
    "students.no_results": "\"{term}\" bo'yicha natijalar yo'q",
    "students.no_students_yet": "Hali talabalar qo'shilmagan",
    "students.mock.2h_ago": "2 soat oldin",
    "students.mock.1d_ago": "1 kun oldin",
    "students.mock.3d_ago": "3 kun oldin",
    "students.mock.30m_ago": "30 daqiqa oldin",
    
    // Student Independent Page
    "student.indep.title": "Mustaqil o'qish",
    "student.indep.subtitle": "Istalgan mavzuni istalgan vaqtda o'rganing",
    "student.indep.streak": "{days} kun streak",
    "student.indep.stat_total_time": "Jami o'qilgan",
    "student.indep.stat_total_time_val": "24 soat",
    "student.indep.stat_topics": "Mavzular",
    "student.indep.stat_topics_val": "18 ta",
    "student.indep.stat_avg_score": "O'rtacha ball",
    "student.indep.stat_streak": "Streak",
    "student.indep.stat_streak_val": "7 kun",
    "student.indep.search_placeholder": "Fan yoki mavzu qidirish...",
    "student.indep.subjects_title": "Fanlarni tanlang",
    "student.indep.subjects_count": "({count} ta fan)",
    "student.indep.subjects_not_found": "\"{term}\" bo'yicha fan topilmadi",
    "student.indep.topics_count": "{count} mavzu",
    "student.indep.custom_topic_title": "O'z mavzungizni kiriting",
    "student.indep.custom_topic_placeholder": "Masalan: Sun'iy intellekt asoslari...",
    "student.indep.learn_btn": "O'rganish",
    "student.indep.upload_title": "Material yuklang",
    "student.indep.upload_analyzing": "Fayl tahlil qilinmoqda...",
    "student.indep.upload_drag": "Faylni bu yerga tashlang yoki bosing",
    "student.indep.upload_formats": "PDF, Word (.doc/.docx) yoki matn (.txt) • Maks 50MB",
    "student.indep.ai_recs_title": "AI tavsiyalari",
    "student.indep.recent_topics_title": "So'nggi mavzular",
    "student.indep.weekly_activity_title": "Haftalik faollik",
    "student.indep.toast_subject_sel": "Mavzu tanlandi",
    "student.indep.toast_subject_desc": "{name} bo'yicha o'qish rejimi ochilmoqda...",
    "student.indep.toast_custom_desc": "{name} bo'yicha o'qish boshlanadi",
    "student.indep.toast_err": "Xatolik",
    "student.indep.toast_err_desc": "Iltimos, mavzu nomini kiriting",
    "student.indep.toast_err_file": "Noto'g'ri fayl turi",
    "student.indep.toast_err_file_desc": "Faqat PDF, Word yoki matn fayllarini yuklash mumkin",
    "student.indep.toast_file_ok": "Fayl yuklandi",
    "student.indep.toast_file_desc": "{name} muvaffaqiyatli yuklandi va tahlil qilindi",
    "student.indep.recent1.title": "React Hooks",
    "student.indep.recent2.title": "Diferensial tenglamalar",
    "student.indep.recent3.title": "Organik kimyo asoslari",
    "student.indep.recent4.title": "Jahon urushi tarixi",
    "student.indep.ai1.title": "React Hooksni takrorlang",
    "student.indep.ai1.reason": "Uzoq vaqt o'rganilmagan",
    "student.indep.ai2.title": "Limit va hosilalar",
    "student.indep.ai2.reason": "Diferensial tenglamalar uchun asos",
    "student.indep.ai3.title": "Kvant mexanikasi",
    "student.indep.ai3.reason": "Fizikadagi yangi mavzu siz uchun",
    
    // Subjects
    "subject.math": "Matematika",
    "subject.math.desc": "Algebra, geometriya, hisob",
    "subject.physics": "Fizika",
    "subject.physics.desc": "Mexanika, termodinamika, kvant",
    "subject.chemistry": "Kimyo",
    "subject.chemistry.desc": "Organik, noorganik, biokimyo",
    "subject.history": "Tarix",
    "subject.history.desc": "Jahon tarixi, O'zbekiston",
    "subject.biology": "Biologiya",
    "subject.biology.desc": "Genetika, ekologiya, anatomiya",
    "subject.languages": "Tillar",
    "subject.languages.desc": "Ingliz, rus, arab tillari",
    "subject.programming": "Dasturlash",
    "subject.programming.desc": "Python, JavaScript, algoritmlar",
    "subject.literature": "Adabiyot",
    "subject.literature.desc": "O'zbek, jahon adabiyoti",
    "subject.geography": "Geografiya",
    "subject.geography.desc": "Jismoniy, iqtisodiy geografiya",
    "subject.economics": "Iqtisodiyot",
    "subject.economics.desc": "Mikro, makroiqtisodiyot",
    
    // Camera
    "camera.enable": "Kamerani yoqish",
    "camera.disable": "Kamerani o'chirish",
    "camera.attention": "Diqqat",
    "camera.students_detected": "Aniqlangan talabalar",
    "camera.snapshot": "Snapshot",
    
    // Common
    "common.save": "Saqlash",
    "common.cancel": "Bekor qilish",
    "common.delete": "O'chirish",
    "common.edit": "Tahrirlash",
    "common.close": "Yopish",
    "common.loading": "Yuklanmoqda...",
    "common.search": "Qidirish",
    "common.filter": "Filtrlash",
    "common.sort": "Saralash",
    "common.apply": "Qo'llash",
    "common.reset": "Qayta o'rnatish",
    "common.confirm": "Tasdiqlash",
    "common.back": "Orqaga",
    "common.next": "Keyingi",
    "common.submit": "Yuborish",
    "common.success": "Muvaffaqiyatli",
    "common.error": "Xato",
    "common.warning": "Ogohlantirish",
    "common.info": "Ma'lumot",
    
    // Theme
    "theme.dark": "Tungi rejim",
    "theme.light": "Kunduzgi rejim",
    "theme.system": "Tizim",
    "theme.title": "Mavzu",
    
    // Language
    "language.title": "Til",
    "language.uz": "O'zbek",
    "language.ru": "Rus",
    "language.en": "English",
  },
  ru: {
    // Navigation
    "nav.home": "Главная",
    "nav.lessons": "Уроки",
    "nav.quizzes": "Тесты",
    "nav.analytics": "Аналитика",
    "nav.settings": "Настройки",
    "nav.profile": "Профиль",
    "nav.logout": "Выход",
    
    // Auth
    "auth.login": "Вход",
    "auth.register": "Регистрация",
    "auth.email": "Email",
    "auth.password": "Пароль",
    "auth.forgot_password": "Забыли пароль?",
    "auth.no_account": "Нет аккаунта?",
    "auth.has_account": "Есть аккаунт?",
    "auth.name": "Имя",
    "auth.role": "Роль",
    "auth.student": "Студент",
    "auth.professor": "Преподаватель",
    
    // Lessons
    "lesson.create": "Создать урок",
    "lesson.join": "Присоединиться",
    "lesson.code": "Код урока",
    "lesson.active": "Активные уроки",
    "lesson.completed": "Завершенные уроки",
    "lesson.start": "Начать",
    "lesson.pause": "Пауза",
    "lesson.resume": "Продолжить",
    "lesson.end": "Завершить",
    "lesson.title": "Название урока",
    "lesson.description": "Описание",
    "lesson.subject": "Предмет",
    "lesson.students_count": "Количество студентов",
    
    // Professor Lessons Page
    "lessons.title": "Мои уроки",
    "lessons.subtitle": "Управление всеми вашими уроками",
    "lessons.search": "Поиск уроков...",
    "lessons.filter_all": "Все",
    "lessons.filter_active": "Активные",
    "lessons.filter_preparing": "Подготавливается",
    "lessons.filter_completed": "Завершенные",
    "lessons.status_active": "Активен",
    "lessons.status_preparing": "Подготавливается",
    "lessons.status_completed": "Завершен",
    "lessons.students": "студентов",
    "lessons.minutes": "минут",
    "lessons.progress": "Прогресс",
    "lessons.manage": "Управлять",
    "lessons.manage_panel": "Панель управления уроком скоро будет запущена.",
    "lessons.not_found_title": "Уроки не найдены",
    "lessons.not_found_search": "Нет результатов по запросу \"{query}\"",
    "lessons.not_found_empty": "Уроки еще не созданы",
    
    // Mock Lessons Data
    "mock.lesson1.title": "Основы баз данных",
    "mock.lesson1.topic": "SQL и реляционные базы данных",
    "mock.lesson1.time": "Завтра 14:00",
    "mock.lesson2.title": "Программная инженерия",
    "mock.lesson2.topic": "Гибкие методологии и SCRUM",
    "mock.lesson2.time": "Пятница 10:00",
    "mock.lesson3.title": "Веб-программирование",
    "mock.lesson3.topic": "Основы React и Next.js",
    "mock.lesson4.title": "Алгоритмы и структуры данных",
    "mock.lesson4.topic": "Алгоритмы сортировки, поиска и графов",
    "mock.lesson4.time": "Понедельник 09:00",
    
    // Live Session Page
    "live.title": "Живой Урок",
    "live.status_live": "В ЭФИРЕ",
    "live.ended_title": "Урок завершен",
    "live.ended_desc": "Подготовка аналитики и результатов...",
    "live.lesson_title": "Урок: Алгоритмы и структуры данных",
    "live.presentation_placeholder": "Презентация будет показана здесь",
    "live.presentation_sub": "Работает с компонентом SlideViewer",
    "live.room_info": "Информация о комнате",
    "live.room_id": "ID комнаты",
    "live.students": "Студенты",
    "live.students_connected": "подключено",
    "live.time": "Время",
    "live.quick_actions": "Быстрые действия",
    "live.send_quiz": "Отправить вопрос",
    "live.end_lesson": "Завершить урок",
    "live.quiz_sent_title": "Вопрос квиза",
    "live.quiz_sent_desc": "Вопрос отправлен на экраны всех студентов!",
    
    // Components (Gauge, Poll)
    "gauge.polling": "Проведите опрос!",
    "gauge.wow_fact": "Покажите WOW-факт!",
    "gauge.interaction": "Спросите студентов!",
    "gauge.title": "Уровень Внимания",
    "gauge.students": "студентов",
    "gauge.confusion": "Путаница",
    "gauge.boredom": "Скука",
    "gauge.good": "Отличное состояние",
    "poll.new": "Новый Опрос",
    "poll.placeholder": "Напишите вопрос...",
    "poll.option": "вариант",
    "poll.start": "Начать Опрос",
    "poll.live": "В ЭФИРЕ",
    "poll.votes": "голосов",
    "poll.total": "Всего:",
    "poll.students": "студентов",
    "poll.end": "Завершить",
    "poll.wait": "Ожидайте начала опроса...",
    "poll.voted": "✓ Ваш голос принят!",
    
    // Analytics Page
    "analytics.title": "Аналитика",
    "analytics.this_week": "Эта неделя",
    "analytics.filters": "Фильтры",
    "analytics.download_pdf": "Скачать PDF",
    "analytics.total_lessons": "Всего уроков",
    "analytics.avg_attention": "Среднее внимание",
    "analytics.avg_quiz_score": "Средний балл тестов",
    "analytics.active_students": "Активные студенты",
    "analytics.timeline_title": "Среднее внимание во время урока (Timeline)",
    "analytics.critical_limit": "Критический предел (70%)",
    "analytics.heatmap_title": "Карта успеваемости по темам",
    "analytics.student": "Студент",
    "analytics.difficulty_title": "Анализ сложности вопросов",
    "analytics.ai_recommendation": "Рекомендация ИИ",
    "analytics.ai_recommendation_desc": "Эти 2 вопроса (Q-12, Q-08) оказались очень сложными. Рекомендуется заново объяснить 'Квантовую энтропию' и 'Формулу плотности'.",
    "analytics.activity_map_title": "Карта активности по дням недели и часам",
    "analytics.activity_map_insight": "💡 Ваша группа проявляет наибольшее внимание в среду с 10:00 до 12:00.",
    "analytics.student_profile": "Профиль студента",
    "analytics.active_student": "Активный студент • 15 дней подряд 🔥",
    "analytics.personal_recommendation": "Персональная рекомендация",
    "analytics.personal_recommendation_desc": "{name} немного испытывает трудности с темой 'Энтропия' (40%). Рекомендуется отправить дополнительные материалы.",
    "analytics.telegram_msg": "Написать сообщение в Telegram",
    "analytics.mastery_details": "Детали успеваемости",
    "analytics.mock.event_start": "Урок начался",
    "analytics.mock.event_drop": "Внимание упало",
    "analytics.mock.event_quiz": "Живой Quiz (Опрос)",
    "analytics.mock.event_fatigue": "Усталость",
    "analytics.mock.event_wow": "Показан WOW-факт",
    "analytics.mock.q1": "Q-12: Квантовая Энтропия",
    "analytics.mock.q2": "Q-08: Формула плотности",
    "analytics.mock.q3": "Q-03: Кинетическая энергия",
    "analytics.mock.q4": "Q-01: Основные концепции",
    "analytics.mock.topic1": "Термодинамика 1",
    "analytics.mock.topic2": "Термодинамика 2",
    "analytics.mock.topic3": "Энтропия",
    "analytics.mock.topic4": "Кинетика",
    
    // Students Page
    "students.title": "Студенты",
    "students.subtitle": "Отслеживайте активность всех студентов",
    "students.add_btn": "Добавить студента",
    "students.error": "Ошибка",
    "students.name_email_required": "Имя и email обязательны",
    "students.added_title": "Студент добавлен!",
    "students.added_desc": "{name} успешно добавлен(а)",
    "students.modal_title": "Добавление нового студента",
    "students.name_label": "Имя и фамилия",
    "students.name_placeholder": "Али Каримов",
    "students.email_label": "Email",
    "students.email_placeholder": "ali@univer.uz",
    "students.cancel": "Отмена",
    "students.add": "Добавить",
    "students.profile_title": "Профиль студента",
    "students.streak_days": "дней серия",
    "students.progress": "Прогресс",
    "students.courses": "Курсы",
    "students.last_active": "Последняя активность:",
    "students.msg_sent_title": "Сообщение отправлено",
    "students.msg_sent_desc": "Отправлен email студенту {name}",
    "students.send_msg": "Отправить сообщение",
    "students.report": "Отчет",
    "students.report_desc": "Уведомление придет, когда отчет будет готов",
    "students.stat_total": "Всего студентов",
    "students.stat_active": "Активные студенты",
    "students.stat_progress": "Средний прогресс",
    "students.stat_streak": "Средняя серия",
    "students.search_placeholder": "Поиск студентов...",
    "students.filter_all": "Все",
    "students.filter_active": "Активные",
    "students.filter_inactive": "Неактивные",
    "students.col_student": "Студент",
    "students.col_progress": "Прогресс",
    "students.col_streak": "Серия",
    "students.col_courses": "Курсы",
    "students.col_status": "Статус",
    "students.col_perf": "Результат",
    "students.col_actions": "Действия",
    "students.days": "дн.",
    "students.perf_excellent": "Отлично",
    "students.perf_good": "Хорошо",
    "students.perf_average": "Средне",
    "students.perf_unknown": "Неизвестно",
    "students.btn_details": "Подробнее",
    "students.btn_msg": "Сообщ.",
    "students.not_found": "Студенты не найдены",
    "students.no_results": "Нет результатов по \"{term}\"",
    "students.no_students_yet": "Студенты еще не добавлены",
    "students.mock.2h_ago": "2 часа назад",
    "students.mock.1d_ago": "1 день назад",
    "students.mock.3d_ago": "3 дня назад",
    "students.mock.30m_ago": "30 минут назад",
    
    // Student Independent Page
    "student.indep.title": "Самостоятельное обучение",
    "student.indep.subtitle": "Изучайте любую тему в любое время",
    "student.indep.streak": "{days} дн. серия",
    "student.indep.stat_total_time": "Всего изучено",
    "student.indep.stat_total_time_val": "24 часа",
    "student.indep.stat_topics": "Темы",
    "student.indep.stat_topics_val": "18 шт",
    "student.indep.stat_avg_score": "Средний балл",
    "student.indep.stat_streak": "Серия",
    "student.indep.stat_streak_val": "7 дней",
    "student.indep.search_placeholder": "Поиск предмета или темы...",
    "student.indep.subjects_title": "Выберите предметы",
    "student.indep.subjects_count": "({count} предметов)",
    "student.indep.subjects_not_found": "Предмет по запросу \"{term}\" не найден",
    "student.indep.topics_count": "{count} тем",
    "student.indep.custom_topic_title": "Введите свою тему",
    "student.indep.custom_topic_placeholder": "Например: Основы искусственного интеллекта...",
    "student.indep.learn_btn": "Изучать",
    "student.indep.upload_title": "Загрузить материал",
    "student.indep.upload_analyzing": "Анализ файла...",
    "student.indep.upload_drag": "Перетащите файл сюда или нажмите",
    "student.indep.upload_formats": "PDF, Word (.doc/.docx) или текст (.txt) • Макс. 50МБ",
    "student.indep.ai_recs_title": "Рекомендации ИИ",
    "student.indep.recent_topics_title": "Недавние темы",
    "student.indep.weekly_activity_title": "Активность за неделю",
    "student.indep.toast_subject_sel": "Предмет выбран",
    "student.indep.toast_subject_desc": "Открывается режим обучения по предмету {name}...",
    "student.indep.toast_custom_desc": "Начинается изучение по теме {name}",
    "student.indep.toast_err": "Ошибка",
    "student.indep.toast_err_desc": "Пожалуйста, введите название темы",
    "student.indep.toast_err_file": "Неверный тип файла",
    "student.indep.toast_err_file_desc": "Можно загрузить только PDF, Word или текстовые файлы",
    "student.indep.toast_file_ok": "Файл загружен",
    "student.indep.toast_file_desc": "{name} успешно загружен и проанализирован",
    "student.indep.recent1.title": "React Hooks",
    "student.indep.recent2.title": "Дифференциальные уравнения",
    "student.indep.recent3.title": "Основы органической химии",
    "student.indep.recent4.title": "История мировой войны",
    "student.indep.ai1.title": "Повторите React Hooks",
    "student.indep.ai1.reason": "Давно не изучалось",
    "student.indep.ai2.title": "Пределы и производные",
    "student.indep.ai2.reason": "Основа для дифференциальных уравнений",
    "student.indep.ai3.title": "Квантовая механика",
    "student.indep.ai3.reason": "Новая тема по физике для вас",
    
    // Subjects
    "subject.math": "Математика",
    "subject.math.desc": "Алгебра, геометрия, вычисления",
    "subject.physics": "Физика",
    "subject.physics.desc": "Механика, термодинамика, квант",
    "subject.chemistry": "Химия",
    "subject.chemistry.desc": "Органическая, неорганическая, биохимия",
    "subject.history": "История",
    "subject.history.desc": "Мировая история, Узбекистан",
    "subject.biology": "Биология",
    "subject.biology.desc": "Генетика, экология, анатомия",
    "subject.languages": "Языки",
    "subject.languages.desc": "Английский, русский, арабский",
    "subject.programming": "Программирование",
    "subject.programming.desc": "Python, JavaScript, алгоритмы",
    "subject.literature": "Литература",
    "subject.literature.desc": "Узбекская, мировая литература",
    "subject.geography": "География",
    "subject.geography.desc": "Физическая, экономическая география",
    "subject.economics": "Экономика",
    "subject.economics.desc": "Микро, макроэкономика",
    
    // Camera
    "camera.enable": "Включить камеру",
    "camera.disable": "Выключить камеру",
    "camera.attention": "Внимание",
    "camera.students_detected": "Обнаружено студентов",
    "camera.snapshot": "Снимок",
    
    // Common
    "common.save": "Сохранить",
    "common.cancel": "Отмена",
    "common.delete": "Удалить",
    "common.edit": "Редактировать",
    "common.close": "Закрыть",
    "common.loading": "Загрузка...",
    "common.search": "Поиск",
    "common.filter": "Фильтр",
    "common.sort": "Сортировка",
    "common.apply": "Применить",
    "common.reset": "Сбросить",
    "common.confirm": "Подтвердить",
    "common.back": "Назад",
    "common.next": "Далее",
    "common.submit": "Отправить",
    "common.success": "Успешно",
    "common.error": "Ошибка",
    "common.warning": "Предупреждение",
    "common.info": "Информация",
    
    // Theme
    "theme.dark": "Темная тема",
    "theme.light": "Светлая тема",
    "theme.system": "Системная",
    "theme.title": "Тема",
    
    // Language
    "language.title": "Язык",
    "language.uz": "Узбекский",
    "language.ru": "Русский",
    "language.en": "English",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.lessons": "Lessons",
    "nav.quizzes": "Quizzes",
    "nav.analytics": "Analytics",
    "nav.settings": "Settings",
    "nav.profile": "Profile",
    "nav.logout": "Logout",
    
    // Auth
    "auth.login": "Login",
    "auth.register": "Register",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.forgot_password": "Forgot password?",
    "auth.no_account": "Don't have an account?",
    "auth.has_account": "Already have an account?",
    "auth.name": "Name",
    "auth.role": "Role",
    "auth.student": "Student",
    "auth.professor": "Professor",
    
    // Lessons
    "lesson.create": "Create Lesson",
    "lesson.join": "Join Lesson",
    "lesson.code": "Lesson Code",
    "lesson.active": "Active Lessons",
    "lesson.completed": "Completed Lessons",
    "lesson.start": "Start",
    "lesson.pause": "Pause",
    "lesson.resume": "Resume",
    "lesson.end": "End",
    "lesson.title": "Lesson Title",
    "lesson.description": "Description",
    "lesson.subject": "Subject",
    "lesson.students_count": "Students Count",
    
    // Professor Lessons Page
    "lessons.title": "My Lessons",
    "lessons.subtitle": "Manage all your lessons",
    "lessons.search": "Search lessons...",
    "lessons.filter_all": "All",
    "lessons.filter_active": "Active",
    "lessons.filter_preparing": "Preparing",
    "lessons.filter_completed": "Completed",
    "lessons.status_active": "Active",
    "lessons.status_preparing": "Preparing",
    "lessons.status_completed": "Completed",
    "lessons.students": "students",
    "lessons.minutes": "minutes",
    "lessons.progress": "Progress",
    "lessons.manage": "Manage",
    "lessons.manage_panel": "Lesson management panel will be launched soon.",
    "lessons.not_found_title": "No lessons found",
    "lessons.not_found_search": "No results for \"{query}\"",
    "lessons.not_found_empty": "No lessons created yet",
    
    // Mock Lessons Data
    "mock.lesson1.title": "Database Fundamentals",
    "mock.lesson1.topic": "SQL and Relational Databases",
    "mock.lesson1.time": "Tomorrow 14:00",
    "mock.lesson2.title": "Software Engineering",
    "mock.lesson2.topic": "Agile methodologies and SCRUM",
    "mock.lesson2.time": "Friday 10:00",
    "mock.lesson3.title": "Web Development",
    "mock.lesson3.topic": "React and Next.js Fundamentals",
    "mock.lesson4.title": "Algorithms and Data Structures",
    "mock.lesson4.topic": "Sort, search and graph algorithms",
    "mock.lesson4.time": "Monday 09:00",
    
    // Live Session Page
    "live.title": "Live Session",
    "live.status_live": "LIVE",
    "live.ended_title": "Lesson ended",
    "live.ended_desc": "Preparing analytics and results...",
    "live.lesson_title": "Lesson: Algorithms and Data Structures",
    "live.presentation_placeholder": "Presentation will be shown here",
    "live.presentation_sub": "Powered by SlideViewer component",
    "live.room_info": "Room Info",
    "live.room_id": "Room ID",
    "live.students": "Students",
    "live.students_connected": "connected",
    "live.time": "Time",
    "live.quick_actions": "Quick Actions",
    "live.send_quiz": "Send Quiz",
    "live.end_lesson": "End Lesson",
    "live.quiz_sent_title": "Quiz Question",
    "live.quiz_sent_desc": "Question sent to all students' screens!",
    
    // Components (Gauge, Poll)
    "gauge.polling": "Conduct a poll!",
    "gauge.wow_fact": "Show a WOW fact!",
    "gauge.interaction": "Ask the students!",
    "gauge.title": "Attention Level",
    "gauge.students": "students",
    "gauge.confusion": "Confusion",
    "gauge.boredom": "Boredom",
    "gauge.good": "Good state",
    "poll.new": "New Poll",
    "poll.placeholder": "Type question...",
    "poll.option": "option",
    "poll.start": "Start Poll",
    "poll.live": "LIVE",
    "poll.votes": "votes",
    "poll.total": "Total:",
    "poll.students": "students",
    "poll.end": "End",
    "poll.wait": "Wait for the poll to start...",
    "poll.voted": "✓ Your vote is recorded!",
    
    // Analytics Page
    "analytics.title": "Analytics",
    "analytics.this_week": "This Week",
    "analytics.filters": "Filters",
    "analytics.download_pdf": "Download PDF",
    "analytics.total_lessons": "Total Lessons",
    "analytics.avg_attention": "Avg Attention",
    "analytics.avg_quiz_score": "Avg Quiz Score",
    "analytics.active_students": "Active Students",
    "analytics.timeline_title": "Average Attention during Lesson (Timeline)",
    "analytics.critical_limit": "Critical Limit (70%)",
    "analytics.heatmap_title": "Topic Mastery Heatmap",
    "analytics.student": "Student",
    "analytics.difficulty_title": "Question Difficulty Analysis",
    "analytics.ai_recommendation": "AI Recommendation",
    "analytics.ai_recommendation_desc": "These 2 questions (Q-12, Q-08) were very difficult. It is recommended to re-explain 'Quantum Entropy' and 'Density Formula'.",
    "analytics.activity_map_title": "Activity Map by Days of Week and Hours",
    "analytics.activity_map_insight": "💡 Your group shows the highest attention on Wednesday between 10:00 and 12:00.",
    "analytics.student_profile": "Student Profile",
    "analytics.active_student": "Active student • 15 day streak 🔥",
    "analytics.personal_recommendation": "Personal Recommendation",
    "analytics.personal_recommendation_desc": "{name} is struggling slightly with 'Entropy' (40%). Sending additional materials is recommended.",
    "analytics.telegram_msg": "Send message via Telegram",
    "analytics.mastery_details": "Mastery Details",
    "analytics.mock.event_start": "Lesson started",
    "analytics.mock.event_drop": "Attention dropped",
    "analytics.mock.event_quiz": "Live Quiz (Polling)",
    "analytics.mock.event_fatigue": "Fatigue",
    "analytics.mock.event_wow": "WOW Fact shown",
    "analytics.mock.q1": "Q-12: Quantum Entropy",
    "analytics.mock.q2": "Q-08: Density Formula",
    "analytics.mock.q3": "Q-03: Kinetic Energy",
    "analytics.mock.q4": "Q-01: Core Concepts",
    "analytics.mock.topic1": "Thermodynamics 1",
    "analytics.mock.topic2": "Thermodynamics 2",
    "analytics.mock.topic3": "Entropy",
    "analytics.mock.topic4": "Kinetics",
    
    // Students Page
    "students.title": "Students",
    "students.subtitle": "Track all students' activity",
    "students.add_btn": "Add student",
    "students.error": "Error",
    "students.name_email_required": "Name and email are required",
    "students.added_title": "Student added!",
    "students.added_desc": "{name} successfully added",
    "students.modal_title": "Add new student",
    "students.name_label": "Full name",
    "students.name_placeholder": "Ali Karimov",
    "students.email_label": "Email",
    "students.email_placeholder": "ali@univer.uz",
    "students.cancel": "Cancel",
    "students.add": "Add",
    "students.profile_title": "Student profile",
    "students.streak_days": "day streak",
    "students.progress": "Progress",
    "students.courses": "Courses",
    "students.last_active": "Last active:",
    "students.msg_sent_title": "Message sent",
    "students.msg_sent_desc": "Email sent to {name}",
    "students.send_msg": "Send message",
    "students.report": "Report",
    "students.report_desc": "You will be notified when the report is ready",
    "students.stat_total": "Total students",
    "students.stat_active": "Active students",
    "students.stat_progress": "Average progress",
    "students.stat_streak": "Average streak",
    "students.search_placeholder": "Search students...",
    "students.filter_all": "All",
    "students.filter_active": "Active",
    "students.filter_inactive": "Inactive",
    "students.col_student": "Student",
    "students.col_progress": "Progress",
    "students.col_streak": "Streak",
    "students.col_courses": "Courses",
    "students.col_status": "Status",
    "students.col_perf": "Performance",
    "students.col_actions": "Actions",
    "students.days": "days",
    "students.perf_excellent": "Excellent",
    "students.perf_good": "Good",
    "students.perf_average": "Average",
    "students.perf_unknown": "Unknown",
    "students.btn_details": "Details",
    "students.btn_msg": "Msg",
    "students.not_found": "No students found",
    "students.no_results": "No results for \"{term}\"",
    "students.no_students_yet": "No students added yet",
    "students.mock.2h_ago": "2 hours ago",
    "students.mock.1d_ago": "1 day ago",
    "students.mock.3d_ago": "3 days ago",
    "students.mock.30m_ago": "30 mins ago",
    
    // Student Independent Page
    "student.indep.title": "Independent Study",
    "student.indep.subtitle": "Study any topic at any time",
    "student.indep.streak": "{days} day streak",
    "student.indep.stat_total_time": "Total studied",
    "student.indep.stat_total_time_val": "24 hours",
    "student.indep.stat_topics": "Topics",
    "student.indep.stat_topics_val": "18",
    "student.indep.stat_avg_score": "Avg Score",
    "student.indep.stat_streak": "Streak",
    "student.indep.stat_streak_val": "7 days",
    "student.indep.search_placeholder": "Search subject or topic...",
    "student.indep.subjects_title": "Select Subjects",
    "student.indep.subjects_count": "({count} subjects)",
    "student.indep.subjects_not_found": "No subject found for \"{term}\"",
    "student.indep.topics_count": "{count} topics",
    "student.indep.custom_topic_title": "Enter your own topic",
    "student.indep.custom_topic_placeholder": "Example: Basics of Artificial Intelligence...",
    "student.indep.learn_btn": "Learn",
    "student.indep.upload_title": "Upload Material",
    "student.indep.upload_analyzing": "Analyzing file...",
    "student.indep.upload_drag": "Drag file here or click",
    "student.indep.upload_formats": "PDF, Word (.doc/.docx) or text (.txt) • Max 50MB",
    "student.indep.ai_recs_title": "AI Recommendations",
    "student.indep.recent_topics_title": "Recent Topics",
    "student.indep.weekly_activity_title": "Weekly Activity",
    "student.indep.toast_subject_sel": "Subject Selected",
    "student.indep.toast_subject_desc": "Opening study mode for {name}...",
    "student.indep.toast_custom_desc": "Starting study for {name}",
    "student.indep.toast_err": "Error",
    "student.indep.toast_err_desc": "Please enter a topic name",
    "student.indep.toast_err_file": "Invalid file type",
    "student.indep.toast_err_file_desc": "Only PDF, Word, or text files can be uploaded",
    "student.indep.toast_file_ok": "File Uploaded",
    "student.indep.toast_file_desc": "{name} successfully uploaded and analyzed",
    "student.indep.recent1.title": "React Hooks",
    "student.indep.recent2.title": "Differential Equations",
    "student.indep.recent3.title": "Basics of Organic Chemistry",
    "student.indep.recent4.title": "History of World War",
    "student.indep.ai1.title": "Review React Hooks",
    "student.indep.ai1.reason": "Not studied for a long time",
    "student.indep.ai2.title": "Limits and Derivatives",
    "student.indep.ai2.reason": "Basis for differential equations",
    "student.indep.ai3.title": "Quantum Mechanics",
    "student.indep.ai3.reason": "New physics topic for you",
    
    // Subjects
    "subject.math": "Mathematics",
    "subject.math.desc": "Algebra, geometry, calculus",
    "subject.physics": "Physics",
    "subject.physics.desc": "Mechanics, thermodynamics, quantum",
    "subject.chemistry": "Chemistry",
    "subject.chemistry.desc": "Organic, inorganic, biochemistry",
    "subject.history": "History",
    "subject.history.desc": "World history, Uzbekistan",
    "subject.biology": "Biology",
    "subject.biology.desc": "Genetics, ecology, anatomy",
    "subject.languages": "Languages",
    "subject.languages.desc": "English, Russian, Arabic",
    "subject.programming": "Programming",
    "subject.programming.desc": "Python, JavaScript, algorithms",
    "subject.literature": "Literature",
    "subject.literature.desc": "Uzbek, world literature",
    "subject.geography": "Geography",
    "subject.geography.desc": "Physical, economic geography",
    "subject.economics": "Economics",
    "subject.economics.desc": "Micro, macroeconomics",
    
    // Camera
    "camera.enable": "Enable Camera",
    "camera.disable": "Disable Camera",
    "camera.attention": "Attention",
    "camera.students_detected": "Students Detected",
    "camera.snapshot": "Snapshot",
    
    // Common
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.close": "Close",
    "common.loading": "Loading...",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.apply": "Apply",
    "common.reset": "Reset",
    "common.confirm": "Confirm",
    "common.back": "Back",
    "common.next": "Next",
    "common.submit": "Submit",
    "common.success": "Success",
    "common.error": "Error",
    "common.warning": "Warning",
    "common.info": "Info",
    
    // Theme
    "theme.dark": "Dark Mode",
    "theme.light": "Light Mode",
    "theme.system": "System",
    "theme.title": "Theme",
    
    // Language
    "language.title": "Language",
    "language.uz": "Uzbek",
    "language.ru": "Russian",
    "language.en": "English",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
  defaultLanguage?: Language;
  storageKey?: string;
}

export function LanguageProvider({
  children,
  defaultLanguage = "uz",
  storageKey = "lectio-language",
}: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>(defaultLanguage);
  const [mounted, setMounted] = useState(false);

  // Initialize language from localStorage
  useEffect(() => {
    const stored = localStorage.getItem(storageKey) as Language | null;
    if (stored && translations[stored]) {
      setLanguageState(stored);
    } else {
      setLanguageState(defaultLanguage);
    }
    setMounted(true);
  }, [defaultLanguage, storageKey]);

  // Update HTML lang attribute
  useEffect(() => {
    if (!mounted) return;
    document.documentElement.lang = language;
  }, [language, mounted]);

  // Set language and persist to localStorage
  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
    localStorage.setItem(storageKey, newLanguage);
  };

  // Translation function
  const t = (key: string, fallback?: string): string => {
    return translations[language][key] || fallback || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        isUZ: language === "uz",
        isRU: language === "ru",
        isEN: language === "en",
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

export type { LanguageContextType };
